version: '3.8'
services:
  torchserve:
    build: ./torchserve
    networks:
      - app-network
    ports:
      - "8080:8080"
      - "8081:8081"

  fastapi:
    build: .
    networks:
      - app-network
    depends_on:
      - torchserve
    ports:
      - "8000:8000"

networks:
  app-network:
    driver: bridge
